### ISSUE TITLE
Asterisk-Call-status has stopped working

### ISSUE THREAD

**Issue by conrad66** [bkbilly/Asterisk-Call-Status#3]
Asterisk-Call-status has stopped working for me.
I updated Debian 11, updated asterisk 18.6.0

At what point it stopped working, I can't figure out
What logs can I see and where ?
In the CLI, I see a connected client.
Asterisk-call-status service is up and running.

In mqtt topic: 'asterisk/callstatus', "idle" all the time
My configuration.yaml
```yaml
asterisk:
  ip: 127.0.0.1
  port: 5038
  user: admin
  pass: 123456789
  dbname: 'astdb'
mqtt:
  topic: 'asterisk/callstatus'
  ip: 192.168.3.210
  user:
  pass:
```
manager.conf in asterisk
```
[general]
enabled = yes
webenabled = yes
timestampevents = yes 
displayconnects = yes 
port = 5038
bindaddr = 127.0.0.1
[admin]
secret =  123456789
deny=0.0.0.0/0.0.0.0
permit = 127.0.0.1
read = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate,message
write = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate,message
```

**Comment by bkbilly** [comment]
One think that I noticed on your configuration is the `bindaddr`, try changing it to the default one `bindaddr = 0.0.0.0`.
Also you can debug why it doesn't get any status changes from the Asterisk CLI.

1. Open a terminal and enable the cli to see the logs: `sudo asterisk -rvvvv`
2. Restart my app: `sudo systemctl restart asterisk_status.service`

On the 1st terminal you should see a log `Manager 'admin' logged on from 127.0.0.1`.
If you see something else like `Connect attempt from 'xxxxxxxxx' unable to authenticate` write it here to help you further.

**Comment by conrad66** [comment]
I have one PC
I fixed my configuration.yml
```
asterisk:
  ip: 127.0.0.1
  port: 5038
  user: admin
  pass: 123456789
  dbname: 'astdb'
mqtt:
  topic: 'asterisk/callstatus'
  ip: 127.0.0.1
  user:
  pass:
```
I fixed my  manager.conf
```
[general]
enabled = yes
webenabled = yes
timestampevents = yes 
displayconnects = yes 

port = 5038
bindaddr = 0.0.0.0

[admin]
secret =  123456789
deny=0.0.0.0/0.0.0.0
permit = 127.0.0.1/255.255.255.255
read = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate,message
write = system,call,log,verbose,command,agent,user,config,command,dtmf,reporting,cdr,dialplan,originate,message
```
After ``` sudo systemctl restart asterisk_status.service```  i see a log ```==Manager 'admin' logged on from 127.0.0.1```
In MQTT Explorer i see ```asterisk/callstatus = idle```, but it doesn't change when you call
